# Generated by Django 4.2.11 on 2024-04-12 19:53

from django.db import migrations, models

def populate_db(apps, schema_editor):
    Movie = apps.get_model("movies", "Movie")
    db_alias = schema_editor.connection.alias

    Movie.objects.using(db_alias).bulk_create([
        Movie(title="Forrest Gump", runtime=142, release_date="1994-07-06"),
        Movie(title="Toy Story", runtime=77, release_date="1995-11-22"),
        Movie(title="Captain Phillips", runtime=134, release_date="2013-10-11"),
        Movie(title="Catch Me If You Can", runtime=141, release_date="2002-12-25"),
        Movie(title="Bridge of Spies", runtime=142, release_date="2015-10-16"),
    ])

def empty_db(apps, schema_editor):
    Movie = apps.get_model("movies", "Movie")
    db_alias = schema_editor.connection.alias

    Movie.objects.using(db_alias).filter(title__in=[
        "Forrest Gump",
        "Toy Story",
        "Captain Phillips",
        "Catch Me If You Can",
        "Bridge of Spies",
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [("movies", "0001_initial")]

    operations = [
        migrations.RunPython(populate_db, empty_db),
    ]
